[[redirects]]
  from = "https://www.immunobase.org.uk/*"
  to = "https://genetics.opentargets.org/immunobase"
  status = 301
  force = true

[[redirects]]
  from = "https://www.immunobase.org/*"
  to = "https://genetics.opentargets.org/immunobase"
  status = 301
  force = true

[[redirects]]
  from = "https://immunobase.org.uk/*"
  to = "https://genetics.opentargets.org/immunobase"
  status = 301
  force = true

[[redirects]]
  from = "https://immunobase.org/*"
  to = "https://genetics.opentargets.org/immunobase"
  status = 301
  force = true

# redirect domain aliases to primary domain
[[redirects]]
  from = "https://genetics.opentargets.io/*"
  to = "https://genetics.opentargets.org/:splat"
  status = 301
  force = true
  
# redirect to ensure longer urls still fetch index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# qa and dev branches to use different apis
# (as per https://github.com/opentargets/genetics/issues/312)
[context.production.environment]
  REACT_APP_GTMID = "GTM-PNQWZ2V"
[context.qa.environment]
  REACT_APP_GRAPHQL_API_URL = "https://genetics-api-qa.opentargets.io"
[context.dev.environment]
  REACT_APP_GRAPHQL_API_URL = "https://open-targets-genetics.appspot.com"
[context."gp-connect-lt".environment]
  REACT_APP_GRAPHQL_API_URL = "https://open-targets-genetics.appspot.com"
[context."gp-intersection".environment]
  REACT_APP_GRAPHQL_API_URL = "https://open-targets-genetics.appspot.com"
